### ISSUE TITLE
Error in Edm2Rdo when saving RDO output to a sql database

### ISSUE THREAD

**Issue by cihanb** [RMS-open-standards/RDOS#12]
Have a sample EDM here : https://github.com/cihanb/RDO_tests/blob/master/EDM-Local-Access/EDM_Test_Orig.bak.zip

and a "sql 2017-ubuntu" running in docker using the following script: https://github.com/cihanb/RDO_tests/blob/master/EDM-Local-Access/restore_edm.sh

I can connect to edm database "db1" and see the EDM. Edm2Rdo works when I set the output to be csv formatted with the following commandline;

**caml113970:osx-x64 cbiyikoglu$ ./Edm2Rdo -i "Data Source=(local);Database=db1;User Id=sa;Password=SA12#45678" --directory . --format csv**

Import Version 1.0 running on .Net (v4.0.30319)
info: EdmToRdoMode[0]
      Reading accounts
info: EdmToRdoMode[0]
      Reading portfolios
info: EdmToRdoMode[0]
      Reading domain data...
info: EdmToRdoMode[0]
      RMS.Rdo.Import.Lookup.DomainLookup
info: EdmToRdoMode[0]
      Domain data read successfully...
██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
100.00% Total (581701 read), 437357 records transformed)                                                                                                                                                                      00:00:11
│ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
├─100.00% Reading (183 accounts, 581701 records)                                                                                                                                                                              00:00:10
│ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
└─100.00% Transforming (581701 -> 437357 records)                                                                                                                                                                             00:00:10`

However, Edm2Rdo fails when the output is set to be Rdo database

**caml113970:osx-x64 cbiyikoglu$ ./Edm2Rdo -i "Data Source=(local);Database=db1;User Id=sa;Password=SA12#45678" -o "Data Source=(local);Database=rdo;User Id=sa;Password=SA12#45678"**

Import Version 1.0 running on .Net (v4.0.30319)
info: EdmToRdoMode[0]
      Creating database rdo
info: EdmToRdoMode[0]
      Database rdo created
info: EdmToRdoMode[0]
      Reading accounts
info: EdmToRdoMode[0]
      Reading portfolios
Unhandled exception. System.AggregateException: One or more errors occurred. (Violation of UNIQUE KEY constraint 'UQ_Portfolio_name'. Cannot insert duplicate key in object 'RDO.Portfolio'. The duplicate key value is (ABC Commercial).
The statement has been terminated.)
 ---> System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'UQ_Portfolio_name'. Cannot insert duplicate key in object 'RDO.Portfolio'. The duplicate key value is (ABC Commercial).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
--- End of stack trace from previous location where exception was thrown ---
   at RMS.Rdo.Import.Writers.SqlRDOModelWriter.BulkCopy(String schema, DataTable dataTable, Action`1 rowsCopied)
   at RMS.Rdo.Import.Writers.SqlRDOModelWriter.WriteAction(DataTable dataTable)
   at RMS.Rdo.Import.Writers.SqlRDOModelWriter.FlushAsync()
   at RMS.Rdo.Import.EdmToRdoMode.WritePortfolios(String outputConnectionString, List`1 portfolios, String outputDirectoryPath, String outputtype)
   at RMS.Rdo.Import.EdmToRdoMode.Run(String inputConnectionString, String outputConnectionString, Boolean singleThreaded, Boolean quietMode, Boolean skipLookupTables, String inputPerilPrecedencePath, String outputDirectoryPath, String outputtype)
ClientConnectionId:435341c8-e2d1-48d1-93cb-ffbed12eb4bf
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Edm2Rdo.Program.EdmToRdo(EdmToRdoOptions options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Edm2Rdo.Program.Main(String[] args)
Abort trap: 6`

**Comment by benhayes21** [comment]
It looks like the RDO.Portfolio table in the target DB has a UNIQUE CONSTRAINT on the name field, which is being violated since your source DB has the same PORTNAME "ABC Commercial" for portfolio id 1 and 5.:

```
ALTER TABLE [RDO].[Portfolio] ADD  CONSTRAINT [UQ_Portfolio_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```

When you do run the csv output option you can see the duplicate names are in the generated portfolio.txt file (even if the headers don't quite line up with the data they describe) :

```
Id~ExternalId~Name~ExposureSetId~Number~PortfolioTypeCode~Description
1~~1~ABC Commercial~3~~
2~~2~ABC Specialty~2~~
3~~3~ABC Insurance~4~~
4~~4~Fast Food US~Fast Food US~3 Accounts, ? Locations~
5~~5~ABC Commercial~3~~  
```

Also, the parquet output option does look like it's working which is great (this didn't appear to be the case for the example EDM provided in this repository)

```
In [1]: import pandas as pd                                                                                                                                                                                              

In [2]: df = pd.read_parquet('Portfolio.parquet')                                                                                                                                                                        

In [3]: df                                                                                                                                                                                                               
Out[3]: 
   Id ExternalId            Name  ExposureSetId        Number PortfolioTypeCode              Description
0   1          1  ABC Commercial              0             3              None                     None
1   2          2   ABC Specialty              0             2              None                     None
2   3          3   ABC Insurance              0             4              None                     None
3   4          4    Fast Food US              0  Fast Food US              None  3 Accounts, ? Locations
4   5          5  ABC Commercial              0             3              None                     None
```

**Comment by cihanb** [comment]
@benhayes21 thanks - that's exactly where the issue is. @vgadiyaram-rms could we get your help in fixing this one?

**Comment by cihanb** [comment]
thanks to the team for the fix. looks like this is expected behavior as EDM allow dup portfolio names while RDO does not.
